Проект на допуск
alatielle/196306-six-cities-5 pull request #1
Opened 2023-10-29 21:14 UTC by alatielle

2023-10-31 20:19 UTC, ElkostVN requested changes

2023-10-31 20:19 UTC, ElkostVN commented on Readme.md
> +* Наставник: `Константин Ильин`.
"Студент" и "Наставник" должны быть одинаковы по форме

2023-10-31 20:19 UTC, ElkostVN commented on docker-compose.dev.yml
> +      MONGO_INITDB_ROOT_PASSWORD: test
Значение для этих ключей стоит брать из `.env`

2023-10-31 20:19 UTC, ElkostVN commented on src/cli/cli-application.ts
> +  constructor(private readonly defaultCommand: string = '--help') {}
Зачем определять это в конструкторе, если значение заранее инициализируется? Оставь это просто пропом класса и убери конструктор

2023-10-31 20:19 UTC, ElkostVN commented on src/cli/cli-application.ts
> +      }
Зачем обращаться к статическим свойствам объекта и переусложнять, если есть более простая проверка:
```
if (this.commands[command.getName()) {
  throw new Error()
}
```

2023-10-31 20:19 UTC, ElkostVN commented on src/cli/command-parser.ts
> +type ParsedCommand = Record<CommandName, CommandArgument[]>;
Все это отлично заменяется записью вида: `Record<string, string[]>`

2023-10-31 20:19 UTC, ElkostVN commented on src/cli/commands/command.interface.ts
> +  run(...parameters: string[]): void;
Неправильный тип в интерфейсе, должен быть `void | Promise<void>`, т.к часть методов run асинхронная

2023-10-31 20:19 UTC, ElkostVN commented on src/cli/commands/help.command.ts
> +        Выводит номер версии
Версии чего?

2023-10-31 20:19 UTC, ElkostVN commented on src/cli/commands/help.command.ts
> +        Печатает этот текст
Какой этот?

2023-10-31 20:19 UTC, ElkostVN commented on src/cli/commands/help.command.ts
> +        Импортирует данные из TSV
Какие данные, куда импортирует?

2023-10-31 20:19 UTC, ElkostVN commented on src/cli/commands/help.command.ts
> +        Генерирует произвольное количество тестовых данных
Куда? Сколько?

2023-10-31 20:19 UTC, ElkostVN commented on src/cli/commands/import.command.ts
> +  private salt: string;
Можно все это сделать readonly, в этом проекте соль не меняется, а остальное является ссылкой на другой объект и не долнжо быть изменено

2023-10-31 20:19 UTC, ElkostVN commented on src/cli/commands/version.command.ts
> +  public run(..._parameters: string[]): void {
Если аргумент не будет использоваться, зачем его оставлять? Разве что для того, чтобы ТС не ругался, но у вас слабый конфиг и он в теории не должен это делать

2023-10-31 20:19 UTC, ElkostVN commented on src/main.cli.ts
> +import 'reflect-metadata';
Не вижу тут чего-либо. что использует этот пакет, для чего он тут?

2023-10-31 20:19 UTC, ElkostVN commented on src/main.cli.ts
> +import { readdirSync } from 'node:fs';
Почему всегда Sync? Стоит брать за привычку использовать методы из fs/promises

2023-10-31 20:19 UTC, ElkostVN commented on src/main.cli.ts
> +}
Жуткий оверхед, тут 4 команды, которые быстрее было бы самостоятельно импортировать

2023-10-31 20:19 UTC, ElkostVN commented on src/main.cli.ts
> +  }
Опять же не вижу предпосылок для динамического импорта

2023-10-31 20:19 UTC, ElkostVN commented on src/rest/rest.application.ts
> +    this.server = express();
Зачем дефайнить это в конструкторе, если можно сделать это сразу на 16 строке?

2023-10-31 20:19 UTC, ElkostVN commented on src/rest/rest.application.ts
> +  private async _initDb() {
Все переменные, свойства и методы должны быть в camelCase, то есть нужно убрать "приватность"

2023-10-31 20:19 UTC, ElkostVN commented on src/rest/rest.application.ts
> +  private async _initServer() {
аналогично

2023-10-31 20:19 UTC, ElkostVN commented on src/rest/rest.application.ts
> +  private async _initControllers() {
аналогично

2023-10-31 20:19 UTC, ElkostVN commented on src/rest/rest.application.ts
> +  private async _initMiddleware() {
аналогично

2023-10-31 20:19 UTC, ElkostVN commented on src/rest/rest.application.ts
> +    this.server.use('/static', express.static('public'));
Зачем два раза?

2023-10-31 20:19 UTC, ElkostVN commented on src/rest/rest.application.ts
> +  private async _initExceptionFilters() {
аналогично

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/helpers/hash.ts
> +import * as crypto from 'node:crypto';
Зачем тащить все содержимое либы, если нужна одна функция? 
`import { createHmac } from 'node:crypto'`

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/helpers/hash.ts
> +};
Раз уж используется лямбда функция, то тогда можно и ван лайнер сделать
```
export const createSHA256 = (line: string, salt: string): string => 
    createHmac('sha256', salt).update(line).digest('hex');
```

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/helpers/offer.ts
> +  return Object.values(enumeration).indexOf(value) !== -1;
Почему бы не упростить до `.includes(value)`

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/helpers/retry.ts
> +}) {
Вынеси это в отдельный интерфейс и используй сразу деструктуризацию параметров

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/helpers/retry.ts
> +      return;
Можно либо убрать return, либо использовать его вместе с callback'ом onSuccess

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/libs/config/rest.schema.ts
> +    default: 5,
Такие дефолтные значения не стоит оставлять в коде

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/libs/config/rest.schema.ts
> +    default: 1000,
Такие дефолтные значения не стоит оставлять в коде

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/libs/file-reader/tsv-file-reader.ts
> +const CHUNK_SIZE = 16384; // 16KB
Константы лежат в отдельном файле

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/libs/offer-generator/tsv-offer-generator.ts
> +  [latitude, longitude].join(';');
сделай это методом класса или перенеси в хелперы

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/libs/rest/controller/base-controller.abstract.ts
> +const DEFAULT_CONTENT_TYPE = 'application/json';
Константы в отдельном файле

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/libs/rest/controller/base-controller.abstract.ts
> +  private readonly _router: Router;
Без `_`, там по условиям camelCase
Если хочешь оставить приватным, сделай через `#`

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/libs/rest/middleware/middleware.interface.ts
> +}
У вас мидлвары асинхронные, значит и тип должен быть соответствующий

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/libs/rest/middleware/parse-token.middleware.ts
> +}
В класс или хэлперы

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/libs/rest/middleware/upload-file.middleware.ts
> +        const fileExtension = extension(file.mimetype);
Можно загрузить любой файл, оно смотрит в content-type, сделай проверку по регулярке/массиву

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/city/city-service.interface.ts
> +  ): Promise<DocumentType<CityEntity>>;
Сущности `City` не существует, поэтому эта логика должна находиться в сервисе офферов

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/city/city.container.ts
> +}
В проекте нет сущности города

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/city/city.controller.ts
> +}
Сущности не существует

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/city/city.entity.ts
> +export const CityModel = getModelForClass(CityEntity);
Сущности не существует

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/city/default-city.service.ts
> +}
Не существует этой сущности в проекте

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/city/dto/create-city.dto.ts
> +  @MaxLength(20, { message: CreateCityValidationMessage.name.maxLength })
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/city/dto/create-city.messages.ts
> +    maxLength: 'Maximum name length must be 20',
Числа должны быть константой

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/comment/comment.controller.ts
> +    }
Есть же мидлвара для этого

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/comment/dto/create-comment.dto.ts
> +  @Length(5, 1024, { message: 'min is 5, max is 1024 ' })
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/comment/dto/create-comment.dto.ts
> +  @Max(5, { message: CreateCommentMessages.rating.maxValue })
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/comment/dto/create-comment.dto.ts
> +  @IsMongoId({ message: CreateCommentMessages.offerId.invalidFormat })
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/comment/dto/create-comment.messages.ts
> +  },
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/coordinates/coordinates.entity.ts
> +}
Под координаты не нужно заводить сущность

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/coordinates/dto/coordinates.dto.ts
> +  @IsLatitude({ message: CoordinatesValidationMessage.latitude.invalidFormat })
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/coordinates/dto/coordinates.dto.ts
> +  })
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/coordinates/dto/coordinates.messages.ts
> +} as const;
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/dto/create-offer.dto.ts
> +    message: CreateOfferValidationMessage.description.maxLength,
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/dto/create-offer.dto.ts
> +  @MaxLength(100, { message: CreateOfferValidationMessage.title.maxLength })
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/dto/create-offer.dto.ts
> +  )
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/dto/create-offer.dto.ts
> +  @MaxLength(256, { message: CreateOfferValidationMessage.image.maxLength })
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/dto/create-offer.dto.ts
> +  @ArrayMaxSize(6, { message: CreateOfferValidationMessage.images.invalidSize })
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/dto/create-offer.dto.ts
> +  @IsBoolean({ message: CreateOfferValidationMessage.premium.invalidFormat })
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/dto/create-offer.dto.ts
> +  })
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/dto/create-offer.dto.ts
> +  @Max(8, { message: CreateOfferValidationMessage.rooms.maxValue })
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/dto/create-offer.dto.ts
> +  @Max(10, { message: CreateOfferValidationMessage.guests.maxValue })
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/dto/create-offer.dto.ts
> +  @Max(100000, { message: CreateOfferValidationMessage.price.maxValue })
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/dto/create-offer.dto.ts
> +  })
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/dto/create-offer.dto.ts
> +  @IsMongoId({ message: CreateOfferValidationMessage.cityId.invalidId })
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/dto/create-offer.messages.ts
> +  },
Вместо магический чисел должны быть константы, сообщение константное, следовательно должно быть в UPPER_CASE

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/dto/update-offer.dto.ts
> +export class UpdateOfferDto {
Аналогично остальным DTO

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/dto/update-offer.messages.ts
> +export const UpdateOfferValidationMessage = {
Аналогично

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/offer.controller.ts
> +    });
Должно быть в контроллере комментариев

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/offer.controller.ts
> +      parseAsInteger(query.limit) ?? 0,
У нас не будет ситуации с лимитом в миллион?

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/offer/offer.controller.ts
> +  }
Зона ответственности комментариев

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/user/dto/create-user.dto.ts
> +export class CreateUserDto {
Аналогично другим ДТО

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/user/dto/create-user.messages.ts
> +export const CreateUserMessages = {
Аналогично

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/user/dto/favorite-offer.dto.ts
> +export class FavoriteOfferDto {
Аналогично другим ДТО

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/user/dto/favorite-offer.messages.ts
> +export const FavoriteOfferMessages = {
Аналогично

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/user/dto/login-user.dto.ts
> +export class LoginUserDto {
Аналогично другим дто

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/user/dto/login-user.messages.ts
> +export const CreateLoginUserMessage = {
Аналогично

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/user/user.controller.ts
> +    });
favorites это подмножество офферов, следовательно и его зона ответственности

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/user/user.controller.ts
> +    }
На этапе мидлвары должна происходить проверка

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/modules/user/user.controller.ts
> +    }
Методы можно оставить здесь, но логику сервиса мувнуть в офферы, хотя бы так

2023-10-31 20:19 UTC, ElkostVN commented on src/shared/types/user-type.enum.ts
> +  Normal = 'Normal',
По ТЗ Pro и Обычный
```
Pro = 'Pro',
Regular = 'Обычный'
```

2023-10-31 20:50 UTC, ruslan4432013 commented on src/main.cli.ts
> +import 'reflect-metadata';
Т.к используются декораторы @inject и @injectable, требуются полифиллы в этом месте

2023-10-31 20:56 UTC, ruslan4432013 commented on src/rest/rest.application.ts
> +  private async _initDb() {
Лайв «Ограничение доступа. Авторизация» 1:12:54 - этот момент разбирали, и такая "приватность" допустима и не нарушает критериев

2023-10-31 21:32 UTC, ruslan4432013 commented on src/shared/modules/offer/offer.controller.ts
> +    });
Не обязательно, согласно демо-проекту (на который говорили ссылаться) https://github.com/htmlacademy-nodejs-api/buy-and-sell-5/pull/7/commits/abc0b52fe6765320b67aedfccf6f540d9e3565c7 можно отсавить в контроллере с оффером

2023-10-31 21:33 UTC, ruslan4432013 commented on src/shared/modules/offer/offer.controller.ts
> +  }
Не обязательно, согласно демо-проекту (на который говорили ссылаться) https://github.com/htmlacademy-nodejs-api/buy-and-sell-5/commit/abc0b52fe6765320b67aedfccf6f540d9e3565c7 можно оставить в контроллере с оффером

2023-10-31 21:59 UTC, alatielle commented on src/main.cli.ts
> +}
На лайве это была задача со звездочкой — сделать динамические импорты. Да, здесь оверхед и руками было бы быстрее. Зато я теперь умею делать динамические импорты :)

2023-10-31 22:09 UTC, alatielle commented on src/rest/rest.application.ts
> +    this.server.use('/static', express.static('public'));
Часть файлов загружается пользователем и попадает в директорию UPLOAD_DIRECTORY. Часть -- статическая (например, стандартный аватар). Их нет смысла держать в одной директории. При этом содержимое обеих должно быть доступно как статика.

В учебном проекте сделано аналогично.

2023-10-31 22:10 UTC, alatielle commented on src/shared/types/user-type.enum.ts
> +  Normal = 'Normal',
Это значение попадет в базу данных. Не думаю, что записывать туда что-то по-русски ок

2023-10-31 22:14 UTC, alatielle commented on src/shared/modules/comment/comment.controller.ts
> +    }
Мидлвара проверяет параметры в path, но не проверяет содержимое body. Стоит ее прокачать?

2023-10-31 22:33 UTC, alatielle commented on docker-compose.dev.yml
> +      MONGO_INITDB_ROOT_PASSWORD: test
Так?
```
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
```

2023-11-04 16:16 UTC, alatielle commented on src/cli/commands/import.command.ts
> +  private salt: string;
Соль приходит из аргументов и присваивается в методе run. По остальному согласна

2023-11-04 16:50 UTC, alatielle commented on src/shared/libs/rest/middleware/middleware.interface.ts
> +}
`ValidateObjectIdMiddleware` не является асинхронной

2023-11-05 21:31 UTC, closed without merging

2023-11-08 22:13 UTC, focuzzzed commented on src/shared/libs/rest/middleware/upload-file.middleware.ts
> +        const fileExtension = extension(file.mimetype);
Интерфейс multer предоставляет типизированное поле fileFilter с ответственной за это функцией

multer({
  storage,
  fileFilter: (req, file, callback) {// условный оператор на коллбэк}
})